version: '3.8'

services:
  app:
    build:
      context: .
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    environment:
      - PORT=${PORT}
      - DATABASE_URL=${DATABASE_URL}
    networks:
      - nodejs2024q3-service_default
    volumes:
      - ./:/app
      - /app/node_modules
    restart: always

  postgres:
    build:
      context: src/database/
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d home_library_db']
      interval: 1m30s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - nodejs2024q3-service_default

volumes:
  postgres:

networks:
  nodejs2024q3-service_default:
    driver: bridge
